bookmarks/bookmarks/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace='images')),

    # python-social-auth is deprecated, doesn't work.
    #url('social-auth/', include('social.apps.django_app.urls', namespace='social')),

    # social-auth-app-django
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    ]

#for django to serve the media files.
#static is only for development mode, not for production.

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^ranking/$', views.image_ranking, name='create'),
    url(r'^$', views.image_list, name='list'),  #retrieves the images either in AJAX pagination way or standard pagination
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse


# model used to store images bookmarks from diff sites.
class Image(models.Model):

    # user that bookmarked this image. FK, bcoz one user, many images.
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='images_created')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)

    # original URL of image.
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)

    # index will be created for this field,
    # time will be automatically added to db.
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)

    # stores the users that like an image. (many users can like many images)
    # so when you want to retrieve this field from USER_MODEL perspective
    # AUTH_USER_MODEL.images_liked (reason for related_name).
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)

    total_likes = models.PositiveIntegerField(db_index=True, default=0)  # to get no of likes in image.

    def __str__(self):
        return self.title

    # overriding the save method to automatically, generate the slug field
    # based on the title field.
    # slugify automatically generates the slug, for the given title, if no slug is provided.
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    """" common pattern to provide canonical url for the objects is to define
         this method in Model"""
    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

bookmarks/images/forms.py
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms
from .models import Image


class ImageCreateForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        """
        users are not going to enter image url directly in form., rather they are going to 
        use javascript tool to choose an image from external site.
        """
        widgets = {
            'url': forms.HiddenInput,
        }

    """
    this fn is used to check the url given has an image or not.
    """
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']

        # split the url to get file extention.
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    """
    Instead of model saving the image into db, we would rather over-ride
    save method of ModelForm class. to save the image into db.
    
    ModelForm's save method allows to save the current instance of the model into db and return the object.
    """
    def save(self, force_insert=False, force_update=False, commit=True):

        # creating an instance but not saving into the database.
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.', 1)[1].lower())

        # download image from the given URL
        response = request.urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)

        """" tells if the image has to be persisted into the database.
         if false it will return an object of ModelForm instance,
         but will not save image into db."""
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_GET
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from common.decorators import ajax_required
from .forms import ImageCreateForm
from .models import Image
from actions.utils import create_action  # To create action to display activity stream (user likes or bookmarked image)
import redis
from django.conf import settings


r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)

"""

We are using Redis here for storing views (like no of persons viewed this image), 
bcoz if we use update queries they would be very complex
and decreases performance, hence we use redis to store Item Views.

"""


@login_required
def image_create(request):
    """
    View for creating an Image using the JavaScript Bookmarklet.
    """
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # assign current user to the item
            new_item.user = request.user
            new_item.save()

            """
            creates an action saying this user has bookmarked this image to display in activity stream.
            """
            create_action(request.user, 'bookmarked image', new_item)

            messages.success(request, 'Image added successfully')
            # redirect to new created item detail view
            return redirect(new_item.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)

    return render(request, 'images/image/create.html', {'section': 'images',
                                                        'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # increment total image views by 1
    total_views = r.incr('image:{}:views'.format(image.id))  # incr increments the value of a key by 1.
    # increment image ranking by 1
    r.zincrby('image_ranking', image.id, 1) # sorted set for image ranking, stores the image id.
    return render(request, 'images/image/detail.html', {'section': 'images',
                                                        'image': image,
                                                        'total_views':total_views})


@ajax_required  # custom decorator, to allow only ajax requests.
@login_required  # requires login
@require_POST  # (requires the request to be POST, does not allow GET requests.)
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')  # action can be like or unlike.
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)  # add objects to related object set, this add avoids duplication

                """creates an action that user liked this image to show in activity stream,"""

                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)  # removes the object from related object set.
            return JsonResponse({'status': 'ok'})  # returning JsonResponse, converting given object into json response
        except:
            pass
    return JsonResponse({'status': 'ko'})


"""
Allows the users to view all bookmarked images.

This fn allows the users to view images in a standard way
and by JAX way with pagination of infinite scrolling.

i.e when user scrolls to bottom of page, we load next page of items via AJAX.
"""


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range return an empty page
            return HttpResponse('')
        # If page is out of range deliver last page of results
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'section': 'images', 'images': images})
    return render(request,
                  'images/image/list.html',
                   {'section': 'images', 'images': images})


"""
View to display the most viewed images.
"""


@login_required
def image_ranking(request):
    """get image ranking dictionary
    zrange (obtains the elements in sorted set), accepts the lowest(0), highest rank(-1) as parameters.
    desc=True to get element in descending score., and gets the first 10 elements.
    """
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # get most viewed images
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,
                  'images/image/ranking.html',
                  {'section': 'images',
                   'most_viewed': most_viewed})

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
    <h1>{{ image.title }}</h1>

     {% load thumbnail %}
    {% thumbnail image.image "300" as im %}
        <a href="{{ image.image.url }}">
            <img src="{{ im.url }}" class="image-detail">
        </a>
    {% endthumbnail %}

    <!-- with template tag is useful to prevent django from executing Queryset multiple times.-->

    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <<div class="image-info">
                <div>
                    <span class="count">
                        <span class="total">{{ total_likes }}</span>
                        like{{ total_likes|pluralize }}
                    </span>
                    <span class="count">
                        <span class="total">{{ total_views }}</span>
                        view{{ total_views|pluralize }}
                    </span>
                <!-- data-id: id of the image displayed, data-action: action to run when user clicks the link (like or unlike) -->
                    <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                        {% if request.user not in users_like %}
                            Like
                        {% else %}
                            Unlike
                        {% endif %}
                    </a>
                </div>
            {{ image.description|linebreaks }}
        </div>

        <div class="image-likes">
            {% for user in image.users_like.all %}
                <div>
                    <img src="{{ user.profile.photo.url }}">
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault(); <!-- to avoid default behaviour of a element like taking us anywhere,-->
        $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'), <!--retrieving these from data-id and data-action attributes. -->
                action: $(this).data('action')
            },
            function(data){
                <!-- this status attribute comes from view, toggling of like to unlike and viceversa happens only if status is OK-->
                if (data['status'] == 'ok')
                {
                     var previous_action = $('a.like').data('action');

                    // toggle data-action
                    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link text
                    $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

                    // update total likes
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                }
        });

    });
{% endblock %}

bookmarks/images/templates/images/image/list.html
<!-- displays the images in standard pagination -->

{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;    <!-- checks if empty page -->
    var block_request = false; <!-- prevents sending an additional request, when an AJAX request is in progress.-->

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200; <!-- (-200) bcoz we make an ajax request when user is 200 px away from reaching end.-->
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
     <!-- data is HTML response-->
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true; <!-- to prevent additional AJAX requests. -->
		        }
		        else {
                    block_request = false;
                    $('#image-list').append(data);
    	        }
            });
    	}
    });
{% endblock %}

bookmarks/images/templates/images/image/list_ajax.html
<!-- displays the images with AJAX pagination of infinite scrolling -->

{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "300x300" crop="100%" as im %}
                <a href="{{ image.get_absolute_url }}">
                    <img src="{{ im.url }}">
                </a>
            {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
        </div>
    </div>
{% endfor %}

bookmarks/images/templates/images/image/ranking.html
{% extends "base.html" %}

{% block title %}Images ranking{% endblock %}

{% block content %}
    <h1>Images ranking</h1>
    <ol>
    {% for image in most_viewed %}
        <li>
            <a href="{{ image.get_absolute_url }}">
                {{ image.title }}
            </a>
        </li>
    {% empty %}
    {% endfor %}
    </ol>
{% endblock %}